package com.nss.simplexweb.enums;

public enum DOCUMENT {

	DOCUMENTS_LIST,
	DOCUMENT_TYPE_LIST,
	DOCUMENT_TRACK_STATUS,
	DOCUMENT_DETAIL,
	DOCUMENT_PARTNER_LIST,
	DOCUMENT_DISPATCHED,
	DOCUMENT_RECEIVED 
}
