package com.nss.simplexweb.enums;

public enum DOCUMENT_CATEGORY_TYPE {
	ALL_DOCUMENT_CATEGORIES_LIST,
	ALL_DOCUMENTS,
	PO_DOCUMENTS,
	INVOICE_PACKING_LIST,
	BL_DOCUMENTS,
	CERTIFICATE_DOCUMENTS,
	OTHER_DOCUMENTS
}
