package com.nss.simplexweb.enums;

public enum NOTIFICATION {
	NOTIFICATION_LIST,
	PUSH_NOTIFICATION,
	REGISTRATION_NOTIFICATION,
	ENQUIRY_NOTIFICATION,
	PO_NOTIFICATION,
	DOCUMENT_NOTIFICATION,
	REGISTRATION,NEW_ENQUIRY,PO,DOCUMENTS
}
