package com.nss.simplexweb.enums;

public enum PO_TRACKING {
	PO_RECEIVED,
	PO_UNDER_PROCESS,
	PO_UNDER_CONFIRMATION,
	PO_CONFIRMED,
	UNDER_PRODUCTION,
	PRODuCTION_COMPLETE,
	DISPATCHED_FROM_FACTORY,
	UNDER_ICD_EXAMINATION,
	RAILED_OUT,
	CONTAINER_READY,
	CONTAINER_DISPATCHED,
	CONTAINER_DELIVERED,
	
	PO_TRACKING_HISTORY_LIST,
	PO_TRACKING_HISTORY,
	PO_NEXT_APPLICABLE_STATUS_TYPE,
	PO_NEXT_APPLICABLE_STATUS_TYPE_LIST,
	PO_STATUS_TYPE_LIST
}
